package main

import (
	"bytes"
	"context"
	"go/format"
	"os"
	"path/filepath"
	"testing"

	"github.com/gechr/clover/internal/constant"
	"github.com/stretchr/testify/require"
)

// TestDescribeFallsBackToRef confirms describe returns the bare ref when src is
// not a git checkout (rev-parse fails), the only branch that is hermetic.
func TestDescribeFallsBackToRef(t *testing.T) {
	t.Parallel()
	require.Equal(t, "main", describe(context.Background(), t.TempDir(), "main"))
}

func TestBackendSpec(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		backend any
		want    string
	}{
		"plain string": {backend: "github:owner/repo", want: "github:owner/repo"},
		"table with full": {
			backend: map[string]any{"full": "ubi:owner/tool"},
			want:    "ubi:owner/tool",
		},
		"table without":    {backend: map[string]any{"options": "x"}, want: ""},
		"non-string field": {backend: map[string]any{"full": 7}, want: ""},
		"unsupported kind": {backend: 42, want: ""},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, backendSpec(tt.backend))
		})
	}
}

func TestRepository(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		backends []any
		want     string
		ok       bool
	}{
		"github backend": {
			backends: []any{"github:owner/repo"},
			want:     "owner/repo",
			ok:       true,
		},
		"aqua backend": {
			backends: []any{"aqua:owner/repo"},
			want:     "owner/repo",
			ok:       true,
		},
		"ubi backend": {
			backends: []any{"ubi:owner/repo"},
			want:     "owner/repo",
			ok:       true,
		},
		"option qualifier dropped": {
			backends: []any{"ubi:owner/repo[exe=rg]"},
			want:     "owner/repo",
			ok:       true,
		},
		"monorepo sub-path":   {backends: []any{"github:owner/repo/sub"}, ok: false},
		"domain-shaped owner": {backends: []any{"aqua:atlassian.com/acli"}, ok: false},
		"empty list":          {backends: nil, ok: false},
		"no github backend":   {backends: []any{"npm:pkg", "cargo:crate"}, ok: false},
		"first github wins": {
			backends: []any{"npm:pkg", "github:first/one", "github:second/two"},
			want:     "first/one",
			ok:       true,
		},
		"table backend": {
			backends: []any{map[string]any{"full": "github:owner/repo"}},
			want:     "owner/repo",
			ok:       true,
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			repo, ok := repository(tt.backends)
			require.Equal(t, tt.ok, ok)
			require.Equal(t, tt.want, repo)
		})
	}
}

func TestBody(t *testing.T) {
	t.Parallel()

	require.Equal(t, []byte("second\nthird\n"), body([]byte("first\nsecond\nthird\n")))
	require.Empty(t, body([]byte("only-one-line")), "a single line with no newline drops to empty")
}

func TestRender(t *testing.T) {
	t.Parallel()

	out, err := render(map[string]entry{
		"zebra":    {provider: constant.ProviderGithub, spec: "z/zebra"},
		"apple":    {provider: constant.ProviderGithub, spec: "a/apple"},
		"black":    {provider: constant.ProviderPypi, spec: "black"},
		"prettier": {provider: constant.ProviderNpm, spec: "@scope/prettier"},
		"magika":   {provider: constant.ProviderCrates, spec: "magika-cli"},
	}, "main@abc1234")
	require.NoError(t, err)

	want := `// Code generated by ./internal/tools/genmise from the mise registry (main@abc1234); DO NOT EDIT.
//
// Regenerate with: go generate ./internal/match

package match

// miseRegistryTools maps mise registry tool names (and aliases) to the GitHub repository their default backend tracks.
var miseRegistryTools = map[string]string{
	"apple": "a/apple",
	"zebra": "z/zebra",
}

// misePypiTools maps mise registry tool names (and aliases) to the PyPI package their pipx backend installs.
var misePypiTools = map[string]string{
	"black": "black",
}

// miseNpmTools maps mise registry tool names (and aliases) to the npm package their npm backend installs.
var miseNpmTools = map[string]string{
	"prettier": "@scope/prettier",
}

// miseCratesTools maps mise registry tool names (and aliases) to the crate their cargo backend installs.
var miseCratesTools = map[string]string{
	"magika": "magika-cli",
}
`
	require.Equal(t, want, string(out))

	// The output is gofmt-canonical, so re-formatting is a no-op.
	reformatted, err := format.Source(out)
	require.NoError(t, err)
	require.Equal(t, out, reformatted)
}

func TestResolve(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		backends []any
		want     entry
		ok       bool
	}{
		"github only": {
			backends: []any{"github:owner/repo"},
			want:     entry{provider: constant.ProviderGithub, spec: "owner/repo"},
			ok:       true,
		},
		"github preferred over co-listed ecosystem": {
			backends: []any{"cargo:crate", "pipx:pkg", "aqua:owner/repo"},
			want:     entry{provider: constant.ProviderGithub, spec: "owner/repo"},
			ok:       true,
		},
		"pipx only": {
			backends: []any{"pipx:ansible"},
			want:     entry{provider: constant.ProviderPypi, spec: "ansible"},
			ok:       true,
		},
		"npm scoped": {
			backends: []any{"npm:@antfu/ni"},
			want:     entry{provider: constant.ProviderNpm, spec: "@antfu/ni"},
			ok:       true,
		},
		"cargo package differs from tool name": {
			backends: []any{"cargo:magika-cli"},
			want:     entry{provider: constant.ProviderCrates, spec: "magika-cli"},
			ok:       true,
		},
		"option qualifier dropped": {
			backends: []any{"cargo:ripgrep[bin=rg]"},
			want:     entry{provider: constant.ProviderCrates, spec: "ripgrep"},
			ok:       true,
		},
		"first ecosystem backend in list order wins": {
			backends: []any{"cargo:crate", "pipx:pkg"},
			want:     entry{provider: constant.ProviderCrates, spec: "crate"},
			ok:       true,
		},
		"unsupported ecosystem skipped": {backends: []any{"core:node", "asdf:plugin"}, ok: false},
		"cargo git url rejected": {
			backends: []any{"cargo:https://example.com/x"},
			ok:       false,
		},
		"empty list": {backends: nil, ok: false},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			got, ok := resolve(tt.backends)
			require.Equal(t, tt.ok, ok)
			require.Equal(t, tt.want, got)
		})
	}
}

func TestRead(t *testing.T) {
	t.Parallel()

	t.Run("empty dir errors", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		_, err := read(dir)
		require.EqualError(t, err, `no registry files under "`+dir+`"`)
	})

	t.Run("malformed toml errors", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		path := filepath.Join(dir, "bad.toml")
		require.NoError(t, os.WriteFile(path, []byte("backends = ["), 0o600))
		_, err := read(dir)
		require.EqualError(
			t,
			err,
			"parse "+path+": toml: line 1 (last key \"backends\"): unexpected EOF; expected value",
		)
	})

	t.Run(
		"resolves github and ecosystem backends, skips curated, adds aliases",
		func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			writeToml := func(name, body string) {
				require.NoError(t, os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600))
			}
			writeToml(
				"ripgrep.toml",
				"backends = [\"github:BurntSushi/ripgrep\"]\naliases = [\"rg\"]\n",
			)
			writeToml(
				"terraform.toml",
				"backends = [\"github:hashicorp/terraform\"]\n",
			) // curated, skipped
			writeToml(
				"leftpad.toml",
				"backends = [\"npm:leftpad\"]\n",
			) // ecosystem-only, resolves to npm
			writeToml(
				"gofmt.toml",
				"backends = [\"gem:gofmt\"]\n",
			) // unsupported ecosystem, skipped

			tools, err := read(dir)
			require.NoError(t, err)
			require.Equal(t, map[string]entry{
				"ripgrep": {provider: constant.ProviderGithub, spec: "BurntSushi/ripgrep"},
				"rg":      {provider: constant.ProviderGithub, spec: "BurntSushi/ripgrep"}, // alias
				"leftpad": {provider: constant.ProviderNpm, spec: "leftpad"},
			}, tools)
		},
	)
}

// TestReadOutputRenders confirms read output feeds render without a format error.
func TestReadOutputRenders(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "gh.toml"),
		[]byte("backends = [\"github:cli/cli\"]\n"), 0o600))

	tools, err := read(dir)
	require.NoError(t, err)
	out, err := render(tools, "main")
	require.NoError(t, err)
	require.True(t, bytes.Contains(out, []byte(`"gh": "cli/cli",`)))
}
