package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestRunWritesMap seeds a registry with one GitHub-backed tool and confirms run
// renders the exact generated map to the output file.
func TestRunWritesMap(t *testing.T) {
	t.Parallel()

	src := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(src, "registry"), 0o750))
	require.NoError(t, os.WriteFile(
		filepath.Join(src, "registry", "foo.toml"),
		[]byte("backends = [\"github:cli/cli\"]\n"), 0o600))

	out := filepath.Join(t.TempDir(), "gen.go")
	require.NoError(t, run(t.Context(), src, "main", out))

	got, err := os.ReadFile(out)
	require.NoError(t, err)

	want := `// Code generated by ./internal/tools/genmise from the mise registry (main); DO NOT EDIT.

package match

// miseRegistryTools maps mise registry tool names (and aliases) to the GitHub
// repository their default backend tracks. Regenerate with:
//
//	go generate ./internal/match
var miseRegistryTools = map[string]string{
	"foo": "cli/cli",
}
`
	require.Equal(t, want, string(got))
}

// TestRunSkipsWhenOnlyRefChanged confirms a second run whose only difference is
// the recorded ref leaves the file bytes untouched (the header-stripped body is
// unchanged).
func TestRunSkipsWhenOnlyRefChanged(t *testing.T) {
	t.Parallel()

	src := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(src, "registry"), 0o750))
	require.NoError(t, os.WriteFile(
		filepath.Join(src, "registry", "foo.toml"),
		[]byte("backends = [\"github:cli/cli\"]\n"), 0o600))

	out := filepath.Join(t.TempDir(), "gen.go")
	require.NoError(t, run(t.Context(), src, "main", out))
	first, err := os.ReadFile(out)
	require.NoError(t, err)

	require.NoError(t, run(t.Context(), src, "other", out))
	second, err := os.ReadFile(out)
	require.NoError(t, err)

	require.Equal(t, first, second)
}

// TestRunMissingRegistry confirms a source without a registry directory yields
// the propagated "no registry files" error.
func TestRunMissingRegistry(t *testing.T) {
	t.Parallel()

	src := t.TempDir()
	out := filepath.Join(t.TempDir(), "gen.go")
	err := run(t.Context(), src, "main", out)
	require.EqualError(t, err, `no registry files under "`+filepath.Join(src, "registry")+`"`)
}
